# Generated by Django 3.2.12 on 2022-08-23 21:34

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220624_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee',
            field=models.IntegerField(blank=True, choices=[(1, 'Yes'), (2, 'No')], default=1, verbose_name='Trabalhador'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_active_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Primeira Data Ativa'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Masculino'), (2, 'Femenino')], default=1, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='/media/default.jpg', upload_to='images/% Y/% m/% d/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_active_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 23, 23, 34, 21, 881854), verbose_name='Última data ativa'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=255, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=255, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='province',
            field=models.CharField(blank=True, max_length=100, verbose_name='Província/Estado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, choices=[('mr', 'Mr.'), ('miss', 'Miss'), ('dr', 'dr.'), ('Dr', 'Dr.')], default='mr', max_length=10, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='user',
            name='vat',
            field=models.CharField(blank=True, max_length=15, verbose_name='Contribuinte'),
        ),
        migrations.AlterField(
            model_name='user',
            name='zip',
            field=models.CharField(blank=True, max_length=100, verbose_name='Caixa Postal'),
        ),
    ]
