# Generated by Django 3.2.12 on 2022-08-28 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220823_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_active_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 28, 8, 47, 56, 421276), verbose_name='Última data ativa'),
        ),
        migrations.AlterField(
            model_name='user',
            name='vat',
            field=models.CharField(blank=True, max_length=15, verbose_name='NUIT'),
        ),
    ]
