# Generated by Django 3.2.12 on 2022-08-28 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220828_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_active_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 28, 8, 54, 9, 751334), verbose_name='Última data ativa'),
        ),
    ]
