# Generated by Django 3.2.12 on 2022-08-14 12:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank', '0004_alter_bankaccount_balance'),
        ('warehouse', '0004_alter_warehouse_active_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('isis', '0103_auto_20220814_1431'),
        ('asset_app', '0070_auto_20220714_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostumerInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.CharField(help_text='Costumer Invoice Number(Ex: Invoice: 12345)', max_length=100, verbose_name='Invoice Number')),
                ('number', models.IntegerField(default=0, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('due_date', models.DateTimeField(default=datetime.datetime(2022, 9, 13, 14, 31, 3, 189713), verbose_name='Due Date')),
                ('credit', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=18)),
                ('debit', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=18)),
                ('total', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=18)),
                ('total_tax', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=18)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=18)),
                ('total_discount', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=18)),
                ('paid_status', models.IntegerField(default=0)),
                ('delivered_status', models.IntegerField(default=0)),
                ('finished_status', models.IntegerField(default=0)),
                ('active_status', models.IntegerField(default=1)),
                ('notes', models.TextField(blank=True, verbose_name='Private Notes')),
                ('public_notes', models.TextField(blank=True, verbose_name='Public Notes')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bank.bankaccount', verbose_name='Bank Account')),
                ('costumer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='asset_app.costumer', verbose_name='Costumer')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='isis.paymentmethod')),
                ('payment_term', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='isis.paymentterm')),
                ('warehouse', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse')),
            ],
            options={
                'ordering': ('number',),
                'unique_together': {('invoice', 'costumer')},
            },
        ),
        migrations.CreateModel(
            name='CostumerReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('active_status', models.IntegerField(blank=True, default=1)),
                ('finished_status', models.IntegerField(blank=True, default=0)),
                ('costumer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='asset_app.costumer')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CostumerInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('price', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('quantity', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('tax_total', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('discount_total', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('sub_total', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('total', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costumer.costumerinvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='isis.product')),
            ],
        ),
        migrations.CreateModel(
            name='CostumerReceiptInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('remaining', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('paid', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costumer.costumerinvoice')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costumer.costumerreceipt')),
            ],
            options={
                'verbose_name': 'Costumer Receipt Invoice',
                'verbose_name_plural': 'Costumer Receipt Invoices',
                'unique_together': {('receipt', 'invoice')},
            },
        ),
    ]
