# Generated by Django 3.2.12 on 2022-08-14 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumerinvoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 14, 31, 29, 141514), verbose_name='Due Date'),
        ),
    ]
