# Generated by Django 3.2.12 on 2022-08-14 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumer', '0002_alter_costumerinvoice_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumerinvoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 22, 42, 50, 258599), verbose_name='Due Date'),
        ),
        migrations.AlterUniqueTogether(
            name='costumerinvoice',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='costumerinvoice',
            name='invoice',
        ),
    ]
