# Generated by Django 3.2.12 on 2022-08-14 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumer', '0003_auto_20220814_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumerinvoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 23, 3, 35, 296369), verbose_name='Due Date'),
        ),
    ]
