# Generated by Django 3.2.12 on 2022-08-20 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumer', '0014_auto_20220819_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumerinvoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 11, 11, 4, 172551), verbose_name='Due Date'),
        ),
    ]
