# Generated by Django 3.2.12 on 2022-08-21 16:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_remove_banktransaction_costumer'),
        ('costumer', '0016_alter_costumerinvoice_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumerreceipt',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bank.bankaccount', verbose_name='Bank Account'),
        ),
        migrations.AlterField(
            model_name='costumerinvoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 20, 18, 25, 32, 344470), verbose_name='Due Date'),
        ),
    ]
