# Generated by Django 3.2.12 on 2022-07-14 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset_app', '0070_auto_20220714_1213'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='Bank Name')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Address')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='Email')),
                ('website', models.URLField(blank=True, max_length=255, verbose_name='Website')),
                ('telephone', models.CharField(blank=True, max_length=255, verbose_name='Telephone')),
                ('fax', models.CharField(blank=True, max_length=255, verbose_name='Fax')),
                ('cell', models.CharField(blank=True, max_length=255, verbose_name='Cell')),
                ('active_status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1, verbose_name='Status')),
                ('notes', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_no', models.CharField(max_length=50, unique=True, verbose_name='Account')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('acc_nib', models.CharField(blank=True, max_length=50, verbose_name='NIB')),
                ('acc_iban', models.CharField(blank=True, max_length=50, verbose_name='IBAN')),
                ('acc_swift', models.CharField(blank=True, max_length=50, verbose_name='SWIFT')),
                ('acc_type', models.IntegerField(choices=[(1, 'Checking'), (2, 'Savings'), (3, 'Money Market'), (4, 'Certificate of Deposit')], default=1, verbose_name='Account Type')),
                ('acc_status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive'), (2, 'Suspended')], default=1, verbose_name='Account Status')),
                ('total_balance', models.DecimalField(decimal_places=6, default=0, editable=False, max_digits=18)),
                ('notes', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bank.bank', verbose_name='Bank')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bank Accounts',
                'ordering': ('acc_no',),
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('notes', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bank.bankaccount')),
                ('costumer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset_app.costumer')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
