# Generated by Django 3.2.12 on 2022-07-14 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_bank_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='total_balance',
            new_name='balance',
        ),
    ]
