# Generated by Django 3.2.12 on 2022-08-17 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_alter_bankaccount_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
    ]
