# Generated by Django 3.2.12 on 2022-08-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_auto_20220818_0146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banktransaction',
            old_name='amount',
            new_name='credit',
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='debit',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
    ]
