# Generated by Django 3.2.12 on 2022-08-20 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_auto_20220820_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banktransaction',
            name='costumer',
        ),
    ]
