# Generated by Django 3.2.12 on 2022-08-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_alter_warehouse_active_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='active_status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1, verbose_name='Active status'),
        ),
    ]
