# Generated by Django 3.2.12 on 2022-08-17 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_alter_warehouse_active_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
    ]
