# Generated by Django 3.2.12 on 2022-07-13 05:38

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0005_alter_supplierinvoice_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierinvoice',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='debit',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='total_discount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='total_tax',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='supplierinvoice',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='supplierinvoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 12, 5, 38, 13, 62911), verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='supplierinvoice',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Private Notes'),
        ),
        migrations.AlterField(
            model_name='supplierinvoice',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
