# Generated by Django 3.2.12 on 2022-07-13 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0007_auto_20220713_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierinvoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 12, 16, 10, 24, 314042), verbose_name='Due Date'),
        ),
    ]
