# Generated by Django 3.2.12 on 2022-07-14 18:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_alter_bankaccount_balance'),
        ('supplier', '0014_auto_20220714_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierinvoice',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bank.bankaccount', verbose_name='Bank Account'),
        ),
        migrations.AlterField(
            model_name='supplierinvoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 13, 18, 56, 24, 738231), verbose_name='Due Date'),
        ),
    ]
