# Generated by Django 3.2.12 on 2022-08-04 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0015_auto_20220714_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierinvoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 3, 15, 22, 52, 257883), verbose_name='Due Date'),
        ),
    ]
