# Generated by Django 3.2.12 on 2022-08-05 14:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset_app', '0070_auto_20220714_1213'),
        ('supplier', '0023_alter_supplierinvoice_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('number', models.IntegerField(default=0, unique=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('active_status', models.IntegerField(blank=True, default=1)),
                ('finished_status', models.IntegerField(blank=True, default=0)),
                ('costumer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='asset_app.costumer')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='supplierinvoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 4, 16, 11, 6, 227349), verbose_name='Due Date'),
        ),
        migrations.CreateModel(
            name='SupplierReceiptInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('remaining', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('paid', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplier.supplierinvoice')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplier.supplierreceipt')),
            ],
            options={
                'verbose_name': 'Supplier Receipt Invoice',
                'verbose_name_plural': 'Supplier Receipt Invoices',
                'unique_together': {('receipt', 'invoice')},
            },
        ),
    ]
