# Generated by Django 3.2.12 on 2022-08-05 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0024_auto_20220805_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierreceipt',
            old_name='costumer',
            new_name='supplier',
        ),
        migrations.AlterField(
            model_name='supplierinvoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 4, 17, 24, 34, 200084), verbose_name='Due Date'),
        ),
    ]
