# Generated by Django 3.2.12 on 2022-08-11 22:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0025_auto_20220805_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplierinvoice',
            options={'ordering': ('number',)},
        ),
        migrations.RemoveField(
            model_name='supplierinvoice',
            name='name',
        ),
        migrations.RemoveField(
            model_name='supplierinvoice',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='supplierreceipt',
            name='name',
        ),
        migrations.RemoveField(
            model_name='supplierreceipt',
            name='slug',
        ),
        migrations.AlterField(
            model_name='supplierinvoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 11, 0, 19, 33, 44342), verbose_name='Due Date'),
        ),
    ]
