# Generated by Django 3.2.12 on 2022-08-11 23:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0026_auto_20220812_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierreceiptinvoice',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='supplierinvoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 11, 1, 37, 27, 449435), verbose_name='Due Date'),
        ),
    ]
