# Generated by Django 3.2.12 on 2022-08-11 23:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0027_auto_20220812_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierinvoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 11, 1, 43, 39, 556286), verbose_name='Due Date'),
        ),
    ]
