# Generated by Django 3.2.12 on 2022-08-18 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0038_auto_20220818_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierinvoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 17, 10, 57, 50, 637640), verbose_name='Due Date'),
        ),
    ]
