# Generated by Django 3.2.12 on 2022-08-21 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0045_auto_20220821_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierinvoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 20, 18, 42, 15, 426437), verbose_name='Due Date'),
        ),
    ]
