# Generated by Django 3.2.12 on 2022-07-14 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isis', '0082_auto_20220713_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='active_status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1),
        ),
        migrations.AlterField(
            model_name='document',
            name='active_status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 13, 12, 13, 18, 901895), verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='invoicing',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 13, 12, 13, 18, 893869), verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='active_status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1),
        ),
        migrations.AlterField(
            model_name='paymentterm',
            name='active_status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='active_status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1),
        ),
        migrations.AlterField(
            model_name='tax',
            name='active_status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1, verbose_name='Status'),
        ),
    ]
