# Generated by Django 3.2.12 on 2022-07-14 16:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_alter_bankaccount_balance'),
        ('isis', '0086_auto_20220714_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bank_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bank.bankaccount', verbose_name='Bank Account'),
        ),
        migrations.AddField(
            model_name='invoicing',
            name='bank_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bank.bankaccount', verbose_name='Bank Account'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 13, 16, 23, 52, 126021), verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='invoicing',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 13, 16, 23, 52, 119964), verbose_name='Due Date'),
        ),
    ]
