# Generated by Django 3.2.12 on 2022-08-05 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isis', '0094_auto_20220805_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptinvoice',
            name='"Remaining"',
        ),
        migrations.AddField(
            model_name='receiptinvoice',
            name='remaining',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 4, 11, 59, 54, 627093), verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='invoicing',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 4, 11, 59, 54, 623104), verbose_name='Due Date'),
        ),
    ]
