# Generated by Django 3.2.12 on 2022-08-17 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isis', '0110_auto_20220817_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='active_status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1, verbose_name='Active status'),
        ),
        migrations.AlterField(
            model_name='document',
            name='active_status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1, verbose_name='Active status'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 16, 23, 56, 28, 746054), verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='invoicing',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 16, 23, 56, 28, 743062), verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='active_status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1, verbose_name='Active status'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='default',
            field=models.IntegerField(blank=True, choices=[(1, 'Yes'), (0, 'No')], default=0),
        ),
        migrations.AlterField(
            model_name='paymentterm',
            name='active_status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1, verbose_name='Active status'),
        ),
        migrations.AlterField(
            model_name='paymentterm',
            name='default',
            field=models.IntegerField(blank=True, choices=[(1, 'Yes'), (0, 'No')], default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='active_status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1, verbose_name='Active status'),
        ),
    ]
