# Generated by Django 3.2.12 on 2022-08-17 23:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_alter_warehouse_notes'),
        ('asset_app', '0071_auto_20220818_0146'),
        ('isis', '0111_auto_20220817_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.IntegerField(blank=True, default=0, verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='document',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='document',
            name='short_name',
            field=models.CharField(default='', max_length=10, unique=True, verbose_name='Short Name'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 17, 1, 46, 9, 934560), verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='isis.paymentmethod', verbose_name='Payment method'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='isis.paymentterm', verbose_name='Payment term'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse', verbose_name='Warehouse'),
        ),
        migrations.AlterField(
            model_name='invoicing',
            name='active_status',
            field=models.IntegerField(default=1, verbose_name='Active Status'),
        ),
        migrations.AlterField(
            model_name='invoicing',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=18, verbose_name='Credit'),
        ),
        migrations.AlterField(
            model_name='invoicing',
            name='debit',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=18, verbose_name='Debit'),
        ),
        migrations.AlterField(
            model_name='invoicing',
            name='delivered_status',
            field=models.IntegerField(default=0, verbose_name='Delivered Status'),
        ),
        migrations.AlterField(
            model_name='invoicing',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 17, 1, 46, 9, 931602), verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='invoicing',
            name='finished_status',
            field=models.IntegerField(default=0, verbose_name='Finished Status'),
        ),
        migrations.AlterField(
            model_name='invoicing',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='invoicing',
            name='paid_status',
            field=models.IntegerField(default=0, verbose_name='Paid Status'),
        ),
        migrations.AlterField(
            model_name='invoicing',
            name='payment_method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='isis.paymentmethod', verbose_name='Payment method'),
        ),
        migrations.AlterField(
            model_name='invoicing',
            name='payment_term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='isis.paymentterm', verbose_name='Payment term'),
        ),
        migrations.AlterField(
            model_name='invoicing',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=18, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='invoicing',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=18, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='invoicing',
            name='total_discount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=18, verbose_name='Total Discount'),
        ),
        migrations.AlterField(
            model_name='invoicing',
            name='total_tax',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=18, verbose_name='Total Tax'),
        ),
        migrations.AlterField(
            model_name='invoicing',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse', verbose_name='Warehouse'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='default',
            field=models.IntegerField(blank=True, choices=[(1, 'Yes'), (0, 'No')], default=0, verbose_name='Default'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='paymentterm',
            name='default',
            field=models.IntegerField(blank=True, choices=[(1, 'Yes'), (0, 'No')], default=0, verbose_name='Default'),
        ),
        migrations.AlterField(
            model_name='paymentterm',
            name='notes',
            field=models.CharField(blank=True, max_length=255, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='product',
            name='area',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='product',
            name='area_units',
            field=models.CharField(blank=True, choices=[('m2', 'm²'), ('dm2', 'dm²'), ('cm2', 'cm²'), ('mm2', 'mm²'), ('ft2', 'ft²'), ('in2', 'in²')], default='m2', max_length=10, verbose_name='Area units'),
        ),
        migrations.AlterField(
            model_name='product',
            name='desired_stock',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='Desired stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='product',
            name='length_units',
            field=models.CharField(blank=True, choices=[('m', 'm'), ('dm', 'dm'), ('cm', 'cm'), ('mm', 'mm'), ('ft', 'ft'), ('in', 'in')], default='m', max_length=10, verbose_name='Length units'),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_purchase_price',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='Max. purchase price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_sell_price',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='Min. Sell price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_stock',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='Min. Stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='product',
            name='physical_stock',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='Physical stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_nature',
            field=models.CharField(blank=True, choices=[('Raw Product', 'Raw Product'), ('Manufactured Product', 'Manufactured Product')], default='Raw Product', max_length=50, verbose_name='Product nature'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_url',
            field=models.URLField(blank=True, max_length=255, verbose_name='Product url'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='Purchase price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_status',
            field=models.IntegerField(choices=[(1, 'For Purchase'), (0, 'Not for Purchase')], default=1, verbose_name='Purchase status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_price',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='Sell price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_price2',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='Sell price 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_price3',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='Sell price 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_price4',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='Sell price 4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_price5',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='Sell price 5'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_status',
            field=models.IntegerField(choices=[(1, 'For Sale'), (0, 'Not for Sale')], default=1, verbose_name='Sell status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_limit',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='Stock limit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='isis.tax', verbose_name='Tax'),
        ),
        migrations.AlterField(
            model_name='product',
            name='volume',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='Volume'),
        ),
        migrations.AlterField(
            model_name='product',
            name='volume_units',
            field=models.CharField(blank=True, choices=[('m3', 'm³'), ('dm3', 'dm³'), ('cm3', 'cm³'), ('mm3', 'mm³'), ('ft3', 'ft³'), ('in3', 'in³'), ('litre', 'litre'), ('gallon', 'gallon')], default=0, max_length=10, verbose_name='Volume units'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_units',
            field=models.CharField(blank=True, choices=[('kg', 'Kg'), ('g', 'G'), ('mg', 'MG'), ('ounce', 'ounce'), ('pound', 'pound'), ('ton', 'ton')], default='kg', max_length=50, verbose_name='Weight units'),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='width'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='active_status',
            field=models.IntegerField(blank=True, default=1, verbose_name='Active status'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='costumer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='asset_app.costumer', verbose_name='Costumer'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='finished_status',
            field=models.IntegerField(blank=True, default=0, verbose_name='Finished status'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='name',
            field=models.CharField(max_length=25, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, unique=True, verbose_name='Rate'),
        ),
    ]
