# Generated by Django 3.2.12 on 2022-08-28 11:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_alter_warehouse_notes'),
        ('bank', '0007_remove_banktransaction_costumer'),
        ('asset_app', '0072_settings_vat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('isis', '0122_auto_20220823_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('number', models.IntegerField(unique=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Invoice Date')),
                ('due_date', models.DateTimeField(default=datetime.datetime(2022, 9, 27, 13, 27, 9, 779835), verbose_name='Due Date')),
                ('paid_status', models.IntegerField(default=0)),
                ('delivered_status', models.IntegerField(default=0)),
                ('finished_status', models.IntegerField(default=0)),
                ('active_status', models.IntegerField(default=1)),
                ('notes', models.TextField(blank=True, verbose_name='Private Notes')),
                ('public_notes', models.TextField(blank=True, verbose_name='Public Notes')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('credit', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=18)),
                ('debit', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=18)),
                ('total', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=18)),
                ('total_tax', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=18)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=18)),
                ('total_discount', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=18)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bank.bankaccount', verbose_name='Bank Account')),
                ('costumer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='asset_app.costumer', verbose_name='Costumer')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-name',),
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 13, 27, 9, 780867), verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='invoicing',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 13, 27, 9, 776877), verbose_name='Due Date'),
        ),
        migrations.CreateModel(
            name='ProductReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('price', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('quantity', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('tax_total', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('discount_total', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('sub_total', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('total', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='isis.product')),
                ('product_return', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='isis.productreturn')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='productreturn',
            name='invoicing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_model', to='isis.invoicing', verbose_name='Select Invoice'),
        ),
        migrations.AddField(
            model_name='productreturn',
            name='modified_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productreturn',
            name='payment_method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='isis.paymentmethod', verbose_name='Payment method'),
        ),
        migrations.AddField(
            model_name='productreturn',
            name='payment_term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='isis.paymentterm', verbose_name='Payment term'),
        ),
        migrations.AddField(
            model_name='productreturn',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse', verbose_name='Warehouse'),
        ),
    ]
